/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_api_v1_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_v1_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations["refresh_api_v1_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register */
    post: operations["register_api_v1_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Categories */
    get: operations["list_categories_api_v1_categories_get"];
    put?: never;
    /** Create */
    post: operations["create_api_v1_categories_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/categories/{category_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update */
    put: operations["update_api_v1_categories__category_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/categories/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detail */
    get: operations["detail_api_v1_categories__slug__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Recipes */
    get: operations["list_recipes_api_v1_recipes_get"];
    put?: never;
    /** Create */
    post: operations["create_api_v1_recipes_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search */
    get: operations["search_api_v1_recipes_search_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/{recipe_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update */
    put: operations["update_api_v1_recipes__recipe_id__put"];
    post?: never;
    /** Delete */
    delete: operations["delete_api_v1_recipes__recipe_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/{recipe_id}/images": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload Image */
    post: operations["upload_image_api_v1_recipes__recipe_id__images_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/{recipe_id}/images/{image_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Image */
    delete: operations["delete_image_api_v1_recipes__recipe_id__images__image_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/{recipe_id}/images/{image_id}/primary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Set Primary Image */
    patch: operations["set_primary_image_api_v1_recipes__recipe_id__images__image_id__primary_patch"];
    trace?: never;
  };
  "/api/v1/recipes/{recipe_id}/ingredients": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Ingredient */
    post: operations["add_ingredient_api_v1_recipes__recipe_id__ingredients_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/{recipe_id}/ingredients/{ingredient_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Ingredient */
    put: operations["update_ingredient_api_v1_recipes__recipe_id__ingredients__ingredient_id__put"];
    post?: never;
    /** Delete Ingredient */
    delete: operations["delete_ingredient_api_v1_recipes__recipe_id__ingredients__ingredient_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/{recipe_id}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Publish */
    patch: operations["publish_api_v1_recipes__recipe_id__publish_patch"];
    trace?: never;
  };
  "/api/v1/recipes/{recipe_id}/steps": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Step */
    post: operations["add_step_api_v1_recipes__recipe_id__steps_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/{recipe_id}/steps/{step_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Step */
    put: operations["update_step_api_v1_recipes__recipe_id__steps__step_id__put"];
    post?: never;
    /** Delete Step */
    delete: operations["delete_step_api_v1_recipes__recipe_id__steps__step_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/{recipe_id}/unpublish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Unpublish */
    patch: operations["unpublish_api_v1_recipes__recipe_id__unpublish_patch"];
    trace?: never;
  };
  "/api/v1/recipes/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detail */
    get: operations["detail_api_v1_recipes__slug__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Live */
    get: operations["live_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AuthorOut
     * @description Public author info only: never the email or roles.
     */
    AuthorOut: {
      /** Avatar Url */
      avatar_url: string | null;
      /** Display Name */
      display_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
    };
    /** Body_upload_image_api_v1_recipes__recipe_id__images_post */
    Body_upload_image_api_v1_recipes__recipe_id__images_post: {
      /** Alt Text */
      alt_text?: string | null;
      /** File */
      file: string;
    };
    /** CategoryCreateRequest */
    CategoryCreateRequest: {
      /** Description */
      description?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Name */
      name: string;
    };
    /** CategoryDetailOut */
    CategoryDetailOut: {
      category: components["schemas"]["CategoryOut"];
      recipes: components["schemas"]["RecipePage"];
    };
    /** CategoryOut */
    CategoryOut: {
      /** Description */
      description: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string | null;
      /** Name */
      name: string;
      /**
       * Recipe Count
       * @default 0
       */
      recipe_count: number;
      /** Slug */
      slug: string;
    };
    /** CategoryRefOut */
    CategoryRefOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
    };
    /** CategoryUpdateRequest */
    CategoryUpdateRequest: {
      /** Description */
      description?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Name */
      name: string;
      /**
       * Order Index
       * @default 0
       */
      order_index: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthEntry */
    HealthEntry: {
      /** Detail */
      detail?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status: "healthy" | "unhealthy";
    };
    /** HealthReport */
    HealthReport: {
      /** Entries */
      entries: {
        [key: string]: components["schemas"]["HealthEntry"];
      };
      /**
       * Status
       * @enum {string}
       */
      status: "healthy" | "unhealthy";
    };
    /** IngredientIn */
    IngredientIn: {
      /** Name */
      name: string;
      /** Notes */
      notes?: string | null;
      /** Order Index */
      order_index?: number | null;
      /** Quantity */
      quantity?: number | string | null;
      /** Unit */
      unit?: string | null;
    };
    /** IngredientOut */
    IngredientOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Notes */
      notes: string | null;
      /** Order Index */
      order_index: number;
      /** Quantity */
      quantity: number | null;
      /** Unit */
      unit: string | null;
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** NutritionIn */
    NutritionIn: {
      /** Calories */
      calories?: number | string | null;
      /** Carbohydrates */
      carbohydrates?: number | string | null;
      /** Fat */
      fat?: number | string | null;
      /** Fiber */
      fiber?: number | string | null;
      /** Protein */
      protein?: number | string | null;
      /** Sodium */
      sodium?: number | string | null;
    };
    /** NutritionOut */
    NutritionOut: {
      /** Calories */
      calories?: number | null;
      /** Carbohydrates */
      carbohydrates?: number | null;
      /** Fat */
      fat?: number | null;
      /** Fiber */
      fiber?: number | null;
      /** Protein */
      protein?: number | null;
      /** Sodium */
      sodium?: number | null;
    };
    /** RecipeCreateRequest */
    RecipeCreateRequest: {
      /**
       * Category Id
       * Format: uuid
       */
      category_id: string;
      /** Cook Time Minutes */
      cook_time_minutes: number;
      /** Description */
      description: string;
      /** @default 1 */
      difficulty: components["schemas"]["RecipeDifficulty"];
      /** Ingredients */
      ingredients?: components["schemas"]["IngredientIn"][];
      nutrition?: components["schemas"]["NutritionIn"] | null;
      /** Prep Time Minutes */
      prep_time_minutes: number;
      /** Servings */
      servings: number;
      /** Steps */
      steps?: components["schemas"]["StepIn"][];
      /** Title */
      title: string;
    };
    /** RecipeDetailOut */
    RecipeDetailOut: {
      author: components["schemas"]["AuthorOut"];
      /**
       * Author Id
       * Format: uuid
       */
      author_id: string;
      category: components["schemas"]["CategoryRefOut"];
      /**
       * Category Id
       * Format: uuid
       */
      category_id: string;
      /** Cook Time Minutes */
      cook_time_minutes: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Description */
      description: string;
      difficulty: components["schemas"]["RecipeDifficulty"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Images */
      images: components["schemas"]["RecipeImageOut"][];
      /** Ingredients */
      ingredients: components["schemas"]["IngredientOut"][];
      nutrition: components["schemas"]["NutritionOut"];
      /** Prep Time Minutes */
      prep_time_minutes: number;
      /** Published At */
      published_at: string | null;
      /** Row Version */
      row_version: number;
      /** Servings */
      servings: number;
      /** Slug */
      slug: string;
      status: components["schemas"]["RecipeStatus"];
      /** Steps */
      steps: components["schemas"]["StepOut"][];
      /** Title */
      title: string;
    };
    /**
     * RecipeDifficulty
     * @enum {integer}
     */
    RecipeDifficulty: 1 | 2 | 3 | 4;
    /** RecipeImageOut */
    RecipeImageOut: {
      /** Alt Text */
      alt_text: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Primary */
      is_primary: boolean;
      /** Medium Url */
      medium_url: string | null;
      /** Order Index */
      order_index: number;
      /** Original Url */
      original_url: string;
      /** Thumbnail Url */
      thumbnail_url: string | null;
    };
    /** RecipeListOut */
    RecipeListOut: {
      /** Has Next Page */
      has_next_page: boolean;
      /** Has Previous Page */
      has_previous_page: boolean;
      /** Items */
      items: components["schemas"]["RecipeSummaryOut"][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Count */
      total_count: number;
      /** Total Pages */
      total_pages: number;
    };
    /** RecipeOut */
    RecipeOut: {
      /**
       * Author Id
       * Format: uuid
       */
      author_id: string;
      /**
       * Category Id
       * Format: uuid
       */
      category_id: string;
      /** Cook Time Minutes */
      cook_time_minutes: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Description */
      description: string;
      difficulty: components["schemas"]["RecipeDifficulty"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Ingredients */
      ingredients: components["schemas"]["IngredientOut"][];
      nutrition: components["schemas"]["NutritionOut"];
      /** Prep Time Minutes */
      prep_time_minutes: number;
      /** Published At */
      published_at: string | null;
      /** Row Version */
      row_version: number;
      /** Servings */
      servings: number;
      /** Slug */
      slug: string;
      status: components["schemas"]["RecipeStatus"];
      /** Steps */
      steps: components["schemas"]["StepOut"][];
      /** Title */
      title: string;
    };
    /** RecipePage */
    RecipePage: {
      /** Items */
      items: components["schemas"]["RecipeSummaryOut"][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Count */
      total_count: number;
      /** Total Pages */
      total_pages: number;
    };
    /** RecipeSearchResultOut */
    RecipeSearchResultOut: {
      /**
       * Author Id
       * Format: uuid
       */
      author_id: string;
      /** Cook Time Minutes */
      cook_time_minutes: number;
      /** Description */
      description: string;
      difficulty: components["schemas"]["RecipeDifficulty"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Prep Time Minutes */
      prep_time_minutes: number;
      /** Published At */
      published_at: string | null;
      /** Relevance Score */
      relevance_score: number;
      /** Servings */
      servings: number;
      /** Slug */
      slug: string;
      status: components["schemas"]["RecipeStatus"];
      /** Title */
      title: string;
    };
    /** RecipeSearchResultsOut */
    RecipeSearchResultsOut: {
      /** Has Next Page */
      has_next_page: boolean;
      /** Has Previous Page */
      has_previous_page: boolean;
      /** Items */
      items: components["schemas"]["RecipeSearchResultOut"][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Count */
      total_count: number;
      /** Total Pages */
      total_pages: number;
    };
    /**
     * RecipeStatus
     * @enum {integer}
     */
    RecipeStatus: 0 | 1 | 2;
    /** RecipeSummaryOut */
    RecipeSummaryOut: {
      /**
       * Author Id
       * Format: uuid
       */
      author_id: string;
      /** Cook Time Minutes */
      cook_time_minutes: number;
      /** Description */
      description: string;
      difficulty: components["schemas"]["RecipeDifficulty"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Prep Time Minutes */
      prep_time_minutes: number;
      /** Published At */
      published_at: string | null;
      /** Servings */
      servings: number;
      /** Slug */
      slug: string;
      status: components["schemas"]["RecipeStatus"];
      /** Title */
      title: string;
    };
    /**
     * RecipeUpdateRequest
     * @description Steps and ingredients are managed through their own endpoints (FR-RCP-009/010).
     */
    RecipeUpdateRequest: {
      /**
       * Category Id
       * Format: uuid
       */
      category_id: string;
      /** Cook Time Minutes */
      cook_time_minutes: number;
      /** Description */
      description: string;
      /** @default 1 */
      difficulty: components["schemas"]["RecipeDifficulty"];
      nutrition?: components["schemas"]["NutritionIn"] | null;
      /** Prep Time Minutes */
      prep_time_minutes: number;
      /** Servings */
      servings: number;
      /** Title */
      title: string;
    };
    /** RegisterRequest */
    RegisterRequest: {
      /** Display Name */
      display_name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /**
     * StepIn
     * @description `step_number` is deliberately absent: the server always assigns it (FR-RCP-010).
     */
    StepIn: {
      /** Description */
      description: string;
      /** Duration Minutes */
      duration_minutes?: number | null;
      /** Image Url */
      image_url?: string | null;
      /** Title */
      title: string;
    };
    /** StepOut */
    StepOut: {
      /** Description */
      description: string;
      /** Duration Minutes */
      duration_minutes: number | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string | null;
      /** Step Number */
      step_number: number;
      /** Title */
      title: string;
    };
    /**
     * UserOut
     * @description Build with `UserOut.model_validate(user)`; never exposes password_hash.
     */
    UserOut: {
      /** Avatar Url */
      avatar_url: string | null;
      /** Display Name */
      display_name: string;
      /** Email */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Roles */
      roles: string[];
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
    };
  };
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
    };
  };
  register_api_v1_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_categories_api_v1_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryOut"][];
        };
      };
    };
  };
  create_api_v1_categories_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_api_v1_categories__category_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  detail_api_v1_categories__slug__get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryDetailOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_recipes_api_v1_recipes_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        category_id?: string | null;
        difficulty?: ("easy" | "medium" | "hard" | "expert") | null;
        max_cook_time?: number | null;
        sort?:
          | "created_at"
          | "-created_at"
          | "title"
          | "-title"
          | "cook_time_minutes"
          | "-cook_time_minutes";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeListOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_api_v1_recipes_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecipeCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_api_v1_recipes_search_get: {
    parameters: {
      query: {
        q: string;
        page?: number;
        page_size?: number;
        category_id?: string | null;
        difficulty?: ("easy" | "medium" | "hard" | "expert") | null;
        max_cook_time?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeSearchResultsOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_api_v1_recipes__recipe_id__put: {
    parameters: {
      query?: never;
      header: {
        "If-Match": number;
      };
      path: {
        recipe_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecipeUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_api_v1_recipes__recipe_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_image_api_v1_recipes__recipe_id__images_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_image_api_v1_recipes__recipe_id__images_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeImageOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_image_api_v1_recipes__recipe_id__images__image_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: string;
        image_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  set_primary_image_api_v1_recipes__recipe_id__images__image_id__primary_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: string;
        image_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeImageOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_ingredient_api_v1_recipes__recipe_id__ingredients_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IngredientIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngredientOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_ingredient_api_v1_recipes__recipe_id__ingredients__ingredient_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: string;
        ingredient_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IngredientIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngredientOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_ingredient_api_v1_recipes__recipe_id__ingredients__ingredient_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: string;
        ingredient_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  publish_api_v1_recipes__recipe_id__publish_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_step_api_v1_recipes__recipe_id__steps_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StepIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StepOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_step_api_v1_recipes__recipe_id__steps__step_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: string;
        step_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StepIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StepOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_step_api_v1_recipes__recipe_id__steps__step_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: string;
        step_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  unpublish_api_v1_recipes__recipe_id__unpublish_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  detail_api_v1_recipes__slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeDetailOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthReport"];
        };
      };
    };
  };
  live_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthReport"];
        };
      };
    };
  };
  ready_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthReport"];
        };
      };
    };
  };
}
