"""full_text_search_title

Revision ID: 21e3398d1493
Revises: ed7e3a2fc1ba
Create Date: 2026-09-25 11:56:31.889296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e3398d1493'
down_revision: Union[str, None] = 'ed7e3a2fc1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent;")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.execute("""
        CREATE OR REPLACE FUNCTION f_unaccent(text)
        RETURNS text AS $$
            SELECT public.unaccent('public.unaccent', $1);
        $$ LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT;
    """)
    op.create_index('idx_recipe_title_trgm_gin', 'recipes', [sa.literal_column('f_unaccent(lower(title))')], unique=False, postgresql_using='gin', postgresql_ops={'f_unaccent(lower(title))': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS unaccent;")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
    op.execute("DROP FUNCTION IF EXISTS f_unaccent;")
    op.drop_index('idx_recipe_title_trgm_gin', table_name='recipes', postgresql_using='gin', postgresql_ops={'f_unaccent(lower(title))': 'gin_trgm_ops'})
    # ### end Alembic commands ###
