"""live step number unique index

Revision ID: ed7e3a2fc1ba
Revises: 71b5175e56f9
Create Date: 2026-09-20 18:12:46.819353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7e3a2fc1ba'
down_revision: Union[str, None] = '71b5175e56f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_recipe_step_number'), 'recipe_steps', type_='unique')
    op.create_index('uq_recipe_step_number', 'recipe_steps', ['recipe_id', 'step_number'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_recipe_step_number', table_name='recipe_steps', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint(op.f('uq_recipe_step_number'), 'recipe_steps', ['recipe_id', 'step_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
